### ISSUE TITLE
cargo build failing

### ISSUE THREAD

**Issue by tmerse** [BrianHicks/tree-grepper#229]
Disclaimer: not a rust user, so there could be an oversight on my side. But `cargo build` mostly worked for me in the past.

Running `cargo build` leads to this error:

```
warning: cc1: fatal error: vendor/tree-sitter-c/src/parser.c: No such file or directory
warning: compilation terminated.

...

error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-I" "vendor/tree-sitter-c/src" "-o" "<PATH_TO_REPO>/tree-grepper/target/debug/build/tree-grepper-1a9b91f5eb854a89/out/vendor/tree-sitter-c/src/parser.o" "-c" "vendor/tree-sitter-c/src/parser.c" with args "cc" did not execute successfully (status code exit status: 1).
```

```
➜  tree-grepper git:(main) cargo --version   
cargo 1.66.0 (d65d197ad 2022-11-15)
➜  tree-grepper git:(main) rustc --version     
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

I used the most recent version of the git repo (commit: `cc93c0330be512860db7e23011093341fb61b2f6` -> "│     Merge pull request #228 from BrianHicks/dependabot/cargo/cc-1.0.78")

**Comment by Mephistophiles** [comment]
Hi, Are you using the nix package manager? It seems the tree-sitter-repo is not cloned.

**Comment by tmerse** [comment]
> Hi, Are you using the nix package manager? It seems the tree-sitter-repo is not cloned.

Not using  nix (but want to look into it somewhere in the future when I have enough free-time allotted). I thought only cloning the repo and than `cd repo && cargo build` would would suffice.

> If you have a Rust toolchain set up, you can also clone this repo and run cargo build.

**Comment by Mephistophiles** [comment]
Oh, you have to clone all repos from this file into vendor folder:

https://github.com/BrianHicks/tree-grepper/blob/main/flake.nix

**Comment by tmerse** [comment]
Thanks for clarifying. I think I'll go with nix than :)
