### ISSUE TITLE
Question: why vendor tree-sitter grammars?

### ISSUE THREAD

**Issue by simonrw** [BrianHicks/tree-grepper#250]
I was wondering why this project vendors the grammars, rather than using the existing Rust crates, e.g. [tree-sitter-rust](https://crates.io/crates/tree-sitter-rust). Is it because the crates are not as up to date?

This may make this project easier to build without Nix, which reduces barrier to entry for contributions (not a problem for me since I'm using Nix/NixOS anyway though).

**Comment by BrianHicks** [comment]
Good question! Simple answer: I couldn't get the crates working when I tried before. If anyone were to want to fix this, I'd recommend they implement #88 instead, as it'd be a more helpful change to how grammars are loaded.

If you'd like to do that yourself, please LMK and we can figure it out together.
