### ISSUE TITLE
`tree-grepper` only seems to print supported languages

### ISSUE THREAD

**Issue by ocharles** [BrianHicks/tree-grepper#290]
I'm running `HEAD`, and

```
❯ tree-grepper -q haskell '(exp_literal (string))' .
c
cpp
elixir
elm
go
haskell
java
javascript
markdown
nix
php
python
ruby
rust
typescript
```

Did this possible regress with https://github.com/BrianHicks/tree-grepper/pull/271?

**Comment by BrianHicks** [comment]
yes, it looks like it may have. I get the same problem on HEAD. That's what I get for not using the latest version of my own software in production. 😆

I'll have a look at fixing it this week! Until then, are you OK with using an older commit?

**Comment by ocharles** [comment]
Sure, I'm trying `b86695abd7d12a497bfd729e7b182480f019bd01` now

**Comment by BrianHicks** [comment]
Alright, I think I've got a fix. I also added some tests so that we won't get another regression (#271 was addressing a CLI regression, and caused another, so it really seems justified!)

**Comment by BrianHicks** [comment]
Thank you for raising this, @ocharles!
