### ISSUE TITLE
Alternative Installation instructions

### ISSUE THREAD

**Issue by danymat** [BrianHicks/tree-grepper#293]
Hello, 

Is it possible to provide an alternative installation instruction, so that we can install on every machine without Nix ?
I saw that most of the code is rust, cargo isn't sufficient ?

Regards,
Danymat

**Comment by BrianHicks** [comment]
If you have the grammars checked out in this way: https://github.com/BrianHicks/tree-grepper/blob/93033a333194e69f8bf11110ff690bcbc95c2f63/flake.nix#L92-L114

… then cargo should be sufficient. It would also be possible to build releases using GitHub actions, but I haven't made that happen yet. You're welcome to give it a go, if you like.
