### ISSUE TITLE
Use Cachix to cache binaries

### ISSUE THREAD

**Issue by bnjmnt4n** [BrianHicks/tree-grepper#35]
I think it would be cool if you could use [Cachix](https://www.cachix.org/) to store binaries, to avoid having to build this on every machine.

**Comment by BrianHicks** [comment]
CI pushes to https://app.cachix.org/cache/tree-grepper on every run :)

**Comment by bnjmnt4n** [comment]
Cool, completely forgot to check the GitHub actions. Maybe this should be added to the docs for better visibility?

**Comment by BrianHicks** [comment]
yes, definitely!

**Comment by BrianHicks** [comment]
https://github.com/BrianHicks/tree-grepper/commit/a6353bd737acdd7be2a7661476d43029fbaaf174 and thanks for the suggestion!
