### ISSUE TITLE
No output when only captures names with `_` are used

### ISSUE THREAD

**Issue by meain** [BrianHicks/tree-grepper#359]
Consider the following query `tree-grepper -q go '((binary_expression (identifier) ["==" "!="] (interpreted_string_literal) @_ri) (#eq? @_ri "\"\""))'`. This does not print out anything even though there are matches. I would expect it to print the `binary_expression`.

It does print if I assign a capture to `binary_expression`. `tree-grepper -q go '((binary_expression (identifier) ["==" "!="] (interpreted_string_literal) @_ri) @exp (#eq? @_ri "\"\""))'`.

**Comment by BrianHicks** [comment]
Hey @meain, this is on purpose. From the README:

> We add one important thing on top of the standard query stuff (including #eq? and #match?): if you name a pattern starting with an underscore, it will not be returned in the output. This is primarily useful for filtering out matches you don't really care about.

(That should probably say “intermediary matches you don’t care about” for clarity.)

This makes life nicer when you’re using tree-grepper primarily on the command line as a human. Is there some specific reason you need a match starting with underscore?

**Comment by meain** [comment]
I understand that we filter out `_ri`, but since there is nothing to show, I expected to see `query`, similar to how `tree-grepper` would have when no captures are specified.

> This makes life nicer when you’re using tree-grepper primarily on the command line as a human. Is there some specific reason you need a match starting with underscore?

Nothing specific, I can add another capture group. But returning empty even though we have matches felt like incorrect behaviour.

**Comment by BrianHicks** [comment]
Yeah, I can see how that would be surprising if you hadn’t seen that behavior before. Would you be up for writing a PR to print some warning to stderr if there are only ignored matches? I’m not likely to be able to get to this soon, but that sounds like a reasonable thing to do to avoid surprises like this for other folks.

**Comment by meain** [comment]
Added https://github.com/BrianHicks/tree-grepper/pull/360
